// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUe_2v88ItM46JtebuvPPnV6NyBPDWJho',
    appId: '1:231834675881:web:349e21f78f6d9bb062d7b8',
    messagingSenderId: '231834675881',
    projectId: 'chat-app-f-48fd1',
    authDomain: 'chat-app-f-48fd1.firebaseapp.com',
    storageBucket: 'chat-app-f-48fd1.appspot.com',
    measurementId: 'G-YZW7NKR086',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYP-jgbrrolswzndJnpRAhKsp3L0BzI1c',
    appId: '1:231834675881:android:056108d4003e856462d7b8',
    messagingSenderId: '231834675881',
    projectId: 'chat-app-f-48fd1',
    storageBucket: 'chat-app-f-48fd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLIPQn3oB4YLp0gjRRioDRYcp6YnkoCKs',
    appId: '1:231834675881:ios:c7afe926c3a2e12162d7b8',
    messagingSenderId: '231834675881',
    projectId: 'chat-app-f-48fd1',
    storageBucket: 'chat-app-f-48fd1.appspot.com',
    iosClientId: '231834675881-sanptce88ebppd5vbvlc31j2sqp4ji9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLIPQn3oB4YLp0gjRRioDRYcp6YnkoCKs',
    appId: '1:231834675881:ios:a0e32d10da82550962d7b8',
    messagingSenderId: '231834675881',
    projectId: 'chat-app-f-48fd1',
    storageBucket: 'chat-app-f-48fd1.appspot.com',
    iosClientId: '231834675881-i8i1rq2pi3qv5j08r6e9jkd0gc0tog5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
